### PR TITLE
Update CMake and README to work with SVA/RBDyn/mc_rbdyn_urdf master

### PR DESCRIPTION
**Pull request by gergondet**
This PR updates the CMake script and the instruction to build the stack with up-to-date SpaceVecAlg, RBDyn and mc_rbdyn_urdf

Depending on how things go with https://github.com/jrl-umi3218/SpaceVecAlg/pull/29 we can amend the instructions

### CODE REVIEW

**Comment by costashatz** [comment]
@gergondet sorry for the late reply! Many things going on!

This looks perfect. @nash169 @walidAmanhoud @fkhadivar can you make sure that this compiles on EPFL machines with latest `jrl-umi3218` libraries and the lib runs ok for iiwa/ROS? If this causes no issues with our code and iiwa can be controlled/compiled smoothly, this is OK with me.

**Comment by gergondet** [comment]
Hi @domire8 @costashatz 

Sorry for the late reply.

I think the issue should go away if you run `git submodule update` in the `mc_rbdyn_urdf` folder (this is an issue with our cmake submodule that has been fixed a while ago)

Thanks for trying it out

**Comment by domire8** [comment]
> Hi @domire8 @costashatz
> 
> Sorry for the late reply.
> 
> I think the issue should go away if you run `git submodule update` in the `mc_rbdyn_urdf` folder (this is an issue with our cmake submodule that has been fixed a while ago)
> 
> Thanks for trying it out

That does not solve the issue. But that's also just a warning, not an error I guess.

**Comment by gergondet** [comment]
> Great! Let us know when you are done to check..

It should be ok on the most recent version.

**Comment by costashatz** [comment]
@domire8 is the fix working now? Thanks!

**Review by domire8 — APPROVED** [review]
Sorry guys, lost track of that but I tested it now and it works fine, without the CMake warning. Good to go! :rocket:

**Comment by costashatz** [comment]
@domire8 @gergondet thanks a lot! **Merging this!**

**Pull request merged**
