### PR TITLE
Publish additional information

### PR DESCRIPTION
**Pull request by costashatz**
Publish additional information:
  - External torques
  - Commanded torques
  - Commanded positions

~~This is WIP...~~

### CODE REVIEW

**Comment by costashatz** [comment]
@JimmyDaSilva sorry for taking too long to merge this. I managed to perform some tests and it is working like a charm. I will fix the conflicts and merge. Thanks for this again!

**Comment by matthias-mayr** [comment]
I merged this into master on my fork and it works for me. Is there something else that should be checked before merging it?

**Comment by costashatz** [comment]
> Is there something else that should be checked before merging it?

Nothing really. Have you experienced any lag or weird issue?

I haven't found time to test it thoroughly. If you tell it is OK, I will merge now..

**Comment by matthias-mayr** [comment]
I double-checked published values with the ones on the SmartPad.
I also plotted the external torque and pushed the robot. The plot looked reasonable.

Maybe @JimmyDaSilva has some more experience with the other information.

**Comment by JimmyDaSilva** [comment]
Hi guys. Actually, I quit using iiwa_ros because I had too many issues with hard real-time control, as mentioned here #36.
I have used the "Additional outputs" back then and the values were great.

I remember investigating if my latency issues were coming from this PR. 
My issues appeared using both the master branch and this PR, and I think with the same consistency.
This is no thorough proof, but I think this PR is ok. Especially thanks to the use of the `realtime_tools::Publisher`

**Comment by JimmyDaSilva** [comment]
Although, it seems the `realtime_tools::Publisher` cannot be used with control frequencies higher than 750Hz because of https://github.com/ros-controls/realtime_tools/issues/14

**Comment by costashatz** [comment]
@JimmyDaSilva @matthias-mayr thank you for your comments.. I will merge asap!

**Pull request merged**
