### PR TITLE
Feature/rehassist modifications

### PR DESCRIPTION
**Pull request by Weyhjin**
Modifications tested and suggested by REHAssist, for double robot control with CustomEffortController.

Fix:
- Connections issues and timeout with Kuka robot
- Remove prefix in robot_description to use ROS namespace instead

Add:
- End effector state publisher, computed during last update state to reuse jacobians (for efficiency)

### CODE REVIEW

**Comment by MichaelBombile** [comment]
Merging of modifications made by Rehassist Lab into the branch: feature/rehassist created from the branch: feature/double-robot-inertia commit: 1c5058855a7a8b76ec168266349e7f96a8d7e575.

**Comment by Elise-J** [comment]
I'm currently testing this pr / new branch.. Thank you for the new features! 

The removal of namespace seems to have broken at least the gazebo simulation for both 1 and 2 robots, I haven't tested it on the real robot yet. 
@Weyhjin Are you using a different simulator? 
I didn't see any namespace added in a launch file, how do you handle two robots at once ?

**Comment by Weyhjin** [comment]
Hi!
We're mainly using RViz for visualization but I had tested the gazebo simulation when I removed the prefix and added the namespaces and it was working. But the launch file for it was on another repo as it had other dependencies, so it is not in this branch. I pasted the files below. I thought I had also corrected the gazebo launch in this branch, but I must have forgotten.

Also as we did not test it since then it may be partially broken now, I'm not sure. But it should be minor changes and should still provide a good example for launching with two robots (you can ignore everything related to the platforms or the task controller). The important part is the `<param name="tf_prefix" value="$(arg model_name)" />` line, which prefixes correctly the robots for the tf transforms. It is also why I removed the hardcoded prefixs in the urdf, as it was redundant and harder to maintain (I had some issue with it at the time).

### virtual_sim.launch
```css
<?xml version="1.0"?>

<launch>
    <!-- Parameters -->
    <arg name="dual" default="true"/>

    <!-- Configure Gazebo -->
    <arg name="world_name" default="$(find iiwa_gazebo)/world/iiwa.world"/>
    <arg name="paused" default="false"/>
    <arg name="use_sim_time" default="true"/>
    <arg name="gui" default="false"/>
    <arg name="headless" default="true"/>
    <arg name="debug" default="false"/>

    <!-- Use Rviz -->
    <arg name="rviz" default="true"/>
    <arg name="rvizconfig" default="$(find task_controller)/config/config.rviz" />

    <!-- Select the controller -->
    <arg name="controller" default="CustomDSControllers"/>

    <!-- Select the robot -->
    <arg name="robot" default="iiwa"/>
    <arg name="model" default="7"/>

    <!-- Select the position of the cobots -->
    <arg name="cob_center_x" default="-0.5"/>
    <arg name="cob_distance_y" default="1.0"/>
    <arg name="cob_y_right" value="$(eval cob_distance_y/2)"/>

    <!-- Calculate robot position, set to rosparam server -->
    <arg name="side_name_left" value="Left"/>
    <arg name="side_name_right" value="Right"/>
    <arg name="cob_left_x" value="$(arg cob_center_x)"/>
    <arg name="cob_left_y" value="$(eval -cob_distance_y/2)"/>
    <arg name="cob_left_z" value="0.0"/>
    <rosparam param="$(arg side_name_left)/$(arg robot)/robot_origin" subst_value="True">[$(arg cob_left_x), $(arg cob_left_y), $(arg cob_left_z)]</rosparam>
    <arg name="cob_right_x" value="$(arg cob_center_x)"/>
    <arg name="cob_right_y" value="$(eval cob_distance_y/2)"/>
    <arg name="cob_right_z" value="0.0"/>
    <rosparam param="$(arg side_name_right)/$(arg robot)/robot_origin" subst_value="True">[$(arg cob_right_x), $(arg cob_right_y), $(arg cob_right_z)]</rosparam>

    <!-- Select the position of the platforms -->
    <arg name="pf_center_x" default="0.5"/>
    <arg name="pf_distance_y" default="0.5"/>
    <arg name="pf_yaw" default="$(eval 90 / 180 * pi)"/>

    <!-- Launch left/right side -->
    <include file="$(find task_controller)/launch/launch_single_side.launch">
        <arg name="virtual_platform" value="true"/>
        <arg name="virtual_cobot" value="true"/>
        <arg name="robot" value="$(arg robot)"/>
        <arg name="model" value="$(arg model)"/>
        <arg name="controller" value="$(arg controller)"/>
        <arg name="side_name" value="$(arg side_name_left)"/>
        <arg name="id" value="left"/>
        <arg name="model_name" value="$(arg robot)_left"/>
        <arg name="cob_x" value="$(arg cob_left_x)"/>
        <arg name="cob_y" value="$(arg cob_left_y)"/>
        <arg name="pf_x" value="$(arg pf_center_x)"/>
        <arg name="pf_y" value="$(eval -pf_distance_y/2)"/>
        <arg name="pf_yaw" value="$(arg pf_yaw)"/>
    </include>
    <include if="$(eval dual)" file="$(find task_controller)/launch/launch_single_side.launch">
        <arg name="virtual_platform" value="true"/>
        <arg name="virtual_cobot" value="true"/>
        <arg name="robot" value="$(arg robot)"/>
        <arg name="model" value="$(arg model)"/>
        <arg name="controller" value="$(arg controller)"/>
        <arg name="side_name" value="$(arg side_name_right)"/>
        <arg name="id" value="right"/>
        <arg name="model_name" value="$(arg robot)_right"/>
        <arg name="cob_x" value="$(arg cob_right_x)"/>
        <arg name="cob_y" value="$(arg cob_right_y)"/>
        <arg name="pf_x" value="$(arg pf_center_x)"/>
        <arg name="pf_y" value="$(eval pf_distance_y/2)"/>
        <arg name="pf_yaw" value="$(arg pf_yaw)"/>
    </include>

    <!-- Loads the Gazebo world -->
    <include file="$(find gazebo_ros)/launch/empty_world.launch">
        <arg name="world_name" value="$(arg world_name)"/>
        <arg name="paused" value="$(arg paused)"/>
        <arg name="use_sim_time" value="$(arg use_sim_time)"/>
        <arg name="gui" value="$(arg gui)" />
        <arg name="headless" value="$(arg headless)"/>
        <arg name="debug" value="$(arg debug)" />
    </include>

    <!-- RViz -->
    <group if="$(arg rviz)">
        <node name="rviz" pkg="rviz" type="rviz" args="-d $(arg rvizconfig)"/>
    </group>

    <!-- Start control node-->
    <!-- launch-prefix="gdb -ex run \-\-args"-->
    <node name="task_controller" ns="task_controller" pkg="task_controller" type="node" output="screen">
        <param name="dual" value="$(eval dual)"/>
        <remap from="/task_controller/Left/foot_interface_output" to="/FI_Output/Left"/>
        <remap from="/task_controller/Right/foot_interface_output" to="/FI_Output/Right"/>
        <remap from="/task_controller/Left/eef_state" to="/$(arg side_name_left)/$(arg robot)/$(arg controller)/eef_state"/>
        <remap from="/task_controller/Right/eef_state" to="/$(arg side_name_right)/$(arg robot)/$(arg controller)/eef_state"/>
        <remap from="/task_controller/Left/foot_interface_input" to="/FI_Input/Left"/>
        <remap from="/task_controller/Right/foot_interface_input" to="/FI_Input/Right"/>
        <remap from="/task_controller/Left/commanding_status" to="/$(arg side_name_left)/$(arg robot)/commanding_status"/>
        <remap from="/task_controller/Right/commanding_status" to="/$(arg side_name_right)/$(arg robot)/commanding_status"/>
        <remap from="/task_controller/Left/update_weight" to="/$(arg side_name_left)/$(arg robot)/$(arg controller)/update_weight"/>
        <remap from="/task_controller/Right/update_weight" to="/$(arg side_name_right)/$(arg robot)/$(arg controller)/update_weight"/>
        <remap from="/task_controller/Left/controller_command" to="/$(arg side_name_left)/$(arg robot)/$(arg controller)/command"/>
        <remap from="/task_controller/Right/controller_command" to="/$(arg side_name_right)/$(arg robot)/$(arg controller)/command"/>
    </node>

</launch>
``` 
### launch_single_side.launch
```css
<?xml version="1.0"?>

<launch>
    <!-- Parameters -->

    <!-- Simulation -->
    <arg name="virtual_platform" default="false"/>
    <arg name="virtual_cobot" default="false"/>

    <!-- Select the robot -->
    <arg name="robot" default="iiwa"/>
    <arg name="model" default="7"/>

    <!-- Select the controller -->
    <arg name="controller" default="CustomDSControllers"/>

    <!-- Names -->
    <arg name="side_name"/>
    <arg name="id" default="$(arg side_name)"/>
    <arg name="model_name" default="$(arg robot)_$(arg id)"/>

    <!-- Position in space -->
    <arg name="cob_x" default="-0.5"/>
    <arg name="cob_y" default="0"/>
    <arg name="pf_x" default="0.5"/>
    <arg name="pf_y" default="0"/>
    <arg name="pf_yaw" default="$(eval 90 / 180 * pi)"/>

    <!-- Launch single side in a group -->
    <group ns="$(arg side_name)">
        <group ns="$(arg robot)">
            <param name="tf_prefix" value="$(arg model_name)" />

            <!-- Configure the controllers -->
            <rosparam file="$(find task_controller)/config/iiwa_control_ds.yaml" command="load" subst_value="True"/>

            <!-- Add the cobot -->
            <include if="$(eval virtual_cobot)" file="$(find iiwa_gazebo)/launch/iiwa_spawner.launch">
                <arg name="model_name" value="$(arg model_name)"/>
                <arg name="iiwa_model" value="$(arg model)"/>
                <arg name="controller" value="$(arg controller)" />
                <arg name="position" value="-x $(arg cob_x) -y $(arg cob_y)"/>
                <arg name="force_sensor" value="false" />
                <arg name="grabber" value="false"/>
            </include>
            <include unless="$(eval virtual_cobot)" file="$(find iiwa_driver)/launch/iiwa_bringup.launch">
                <arg name="model" value="$(arg model)"/>
                <arg name="controller" value="$(arg controller)" />
            </include>

            <!-- tf transform to position robot base in world-->
            <node pkg="tf2_ros" type="static_transform_publisher" name="world_to_$(arg model_name)" args="$(arg cob_x) $(arg cob_y) 0 0 0 0 1 world $(arg model_name)/base_link" />
        </group>
    </group>

    <!-- Adds the platform TEMP outside of group due to URDF namespace issue -->
    <include file="$(find foot_platform_ros)/launch/platform_ros.launch">
        <arg name="id" value="$(arg id)" />
        <arg name="virtual_platform" value="$(arg virtual_platform)" />
        <arg name="rviz" value="false"/>
        <arg name="position_xyz" value="$(eval str(pf_x)+' '+str(pf_y)+' 0')"/>
        <arg name="position_ypr" value="$(eval str(pf_yaw)+' 0 0')"/>
    </include>
</launch>
``` 

Sorry for the mess, we had to develop in a hurry at the time. Tell me if you miss something!

**Comment by Weyhjin** [comment]
Otherwise if it's breaking too much the rest, you can also revert the iiwa_description package. The most important changes for the stability are on the iiwa.cpp/iiwa.h files.

**Comment by Weyhjin** [comment]
Also, last message, sorry for the spam. It is not directly related but we had some issue with the PositionController (type: position_controllers/JointGroupPositionController). I'm mentioning it, as it seems to be used in the controllers.yaml? It looks like a stability/connection issue (the movements are noisy/jumpy). I lost a lot of time looking into that direction, but I suspect it too be more related to a problem with the lower level pid controller, which is too sensible to the low communication frequency. I replaced it in another branch by the CustomEffortController (with the type PidController) and all problems disappeared, with a very smooth and tuneable control.

**Comment by Elise-J** [comment]
Hi,
Perfect thank you! I was able to make the gazebo work with small modifications. 
I had to put the link "world" in the urdf otherwise the robot falls down in gazebo and I added the namespace in a few launch file so it is still compatible with other repo on our side that using iiwa_ros.

For the PositionController, I have honestly never used it, we always use the TorqueController.. But it's good to know, I'll add a comment

**Pull request merged**
